### ISSUE TITLE
How to get more than 20 results?

### ISSUE THREAD

**Issue by isalmanhaider** [MickeyUK/places-scraper#2]
Awesome code, however it only returns 20 results, how do I get more than 20 results?

**Comment by PManager1** [comment]
Plus one

**Comment by PManager1** [comment]
Did you find any better way @isalmanhaider

**Comment by MickeyUK** [comment]
I've updated this project to be a standalone app, that now returns more than 20 results at once: 
https://github.com/MickeyUK/map-email-scraper/releases/tag/2.00
